### PR TITLE
Dynamic timezone menu

### PR DESCRIPTION
**Pull request by bentumbler**
Reads the timezone list and uses it to create the menus to set one of the timezones
Arranged into country menus to allow for easier searching

Known issue: Timezone display is the actual timezone value and some of these are too long to fit on the screen. An enhancement could be to remove the country from the final printed value and then rejoin it to the country when calling the function.

### CODE REVIEW

**Comment by joshschmelzle** [comment]
I'd like to see more of a pure Python implementation. One where the enhancement isn't coupled to a bash script managed by different package. The goal being minimizing outside dependencies where possible. Other maintainers may feel otherwise and proceed with merging.

**Comment by bentumbler** [comment]
This effort was to convert the existing approach (limited to 2 time zones and using the underlying bash script) to one which allowed all time zones to be available. 

It is my opinion that it would be a new feature to convert bash dependent features to pure python. As the bash scripts are used elsewhere, outside of FPMS, we might want to avoid maintaining the feature in multiple places (Bash and pure python) so this probably needs more discussion first.

**Comment by joshschmelzle** [comment]
I agree with the effort to flush out the feature and all your points.

My caution is as more components are stitched and strung together the more possible future rabbit holes for break-fix.

In this case, wlanpi-timezone is a convenience CLI wrapper around timedatectl.

That aside, I did quickly test this PR and it seems to work for me, but I prefer if Nigel reviews and merges.

**Comment by joshschmelzle** [comment]
The known issue seems to impact the TZs in America more than Europe. Some are completely unreadable. For my geo, scrolling down to America/New York takes a while, but should be a one time thing, so only a minor annoyance.

**Comment by bentumbler** [comment]
This shortens the printed timezone by not showing the country, but it fails for UTC time where it does not follow the convention of country/timezone.

There are now 4 options and a decision by the package owner / team is needed
1. Adjust wlanpi-timezones for UTC to become UTC/UTC
2. Adjust this wrapper to work with UTC - e.g. identify it differently in the menu such as *UTC (not a preferred option)
3. Implement native (as per Josh's suggestion)
4. Do not accept this change and allow overflowing timezones on screen (Not a preferred option)

**Comment by wifinigel** [comment]
Overall, I really like this implementation. Longer term, I agree that we need to base this on something that isn't based on CLI command wrappers (like many other things we've done). Longer term, we'll have a back-end API endpoint to call to get this data. I think that enough time has probably been spent on this and we should revisit when we get the endpoint available.

1. UTC entry: I think that, as suggested, UTC to become UTC/UTC for now
2. I think the continent/location hierarchy works really well for 90% of the entries. It falls apart for the some of the Argentina/xxx, Indiana/xxx type entries, but would still be understandable I think it there was a hard truncation after 16 characters. This would still allow the navigation arrow to be visible at the right of each entry. I feel there are enough letters visible for someone who knows that area to figure out the location from the information visible.

Considering the limitations of the OLED display, this a really nice piece of work. I'm sure people will be quite forgiving when using it, given the real-estate available. Given the effort that has been put in to this, I'd like to see it included.

**Comment by joshschmelzle** [comment]
Do we want this included in the Prague release?

**Comment by joshschmelzle** [comment]
Known issue right now is UTC will not work until wlanpi-timezone handles it. @jiribrejcha can you review?

**Comment by joshschmelzle** [comment]
Thanks Ben for the enhancement!

**Pull request merged**
